### ISSUE TITLE
Using resium behind a firewall

### ISSUE THREAD

**Issue by bling683** [darwin-education/resium#119]
I'm currently having issues getting the globe/map to render. I looks like Cesium is trying to reach out to `https://api.cesium.com` site to authenticate the ion default token. What if you're behind a firewall and you can't reach out to that site? Is there a way to disable that part of the workflow and just have resium utilize cesiumjs behind the hood?

**Comment by rot1024** [comment]
You can use other ImageryProvider. For example:

- OpenStreetMapImageryProvider
- BingMapsImageryProvider
- GoogleEarthImageryProvider
- SingleTileImageryProvider
- WebMapServiceImageryProvider
- WebMapTileServiceImageryProvider
- UrlTemplateImageryProvider

```jsx
const provider = new OpenStreetMapImageryProvider({ ... });

// -----

<Viewer imageryProvider={provider} />
```

Note: this issue is related to Cesium, not to Resium.

**Comment by bling683** [comment]
Thanks, @rot1024. That's the snippet I tried prior. Unfortunately, it seems like Cesium forces to authenticate with the `https://api.cesium.com`. Which I can't get to. Thus, it seems to just halt rendering after that. 

I'll raise this question to the Cesium forum. Thanks.
