### ISSUE TITLE
Billboard component problem?

### ISSUE THREAD

**Issue by Luyonzhang1993** [darwin-education/resium#131]
Hi!
I hava a question?
My Billboard has moved when my camera move.

First
![20191114142757](https://user-images.githubusercontent.com/18494103/68832108-076ebb00-06eb-11ea-8c45-b9ab785c4d2b.jpg)

Second Move
![20191114142818](https://user-images.githubusercontent.com/18494103/68832178-3be27700-06eb-11ea-93f1-45d8fa638ffa.jpg)

**Comment by rot1024** [comment]
Please provide your source code.

**Comment by Luyonzhang1993** [comment]
thanks, here is my code.
resium: ^1.8.1
cesium: ^1.62.0
react: ^16.10.2

JSX content
![20191114165151](https://user-images.githubusercontent.com/18494103/68841239-368f2780-06ff-11ea-8651-be193d5e276e.jpg)

reservoirData
![20191114165426](https://user-images.githubusercontent.com/18494103/68841363-75bd7880-06ff-11ea-8e28-756c3097b3b1.jpg)

**Comment by rot1024** [comment]
I recommend to use `Entity` and `BillboardGraphics` component instead of `BillboardCollection` and `Billboard` component.

If you do not specify proper `modelMatrix` property on `BillboardCollection` component, the billboard may not be displayed at the intended location. If you want to place a billboard at any latitude and longitude, it is easiest to use `Entity` and `BillboardGraphics` component as bellow.

```jsx
<Viewer full>
  <Entity
    name="BillboardGraphics"
    description="BillboardGraphics!!"
    position={Cartesian3.fromDegrees(-40.0707383, 40.7117244, 100)}>
    <BillboardGraphics image="hoge.png" />
  </Entity>
</Viewer>
```

**Comment by Luyonzhang1993** [comment]
Thanks, rot1024.
