### ISSUE TITLE
ReactJS - setState causes viewer to re-render every time

### ISSUE THREAD

**Issue by mhaque02** [darwin-education/resium#372]
When using Resium with ReactJS and adding an `ImageLayer`, it is causing the viewer to refresh every time any `setState` is called. How can I use `setState` to update certain parts of the page without re-rendering the map?

Example below and screenshot of the issue

` 
class LiveMap extends React.PureComponent {
    viewerRef = React.createRef();
    state = {
        name: "test"
    };
  
    handleSelectedEntityChanged = (event) => {
        console.log("selected: " + event);
        this.setState({
            ...this.state,
            name: this.state.name === "test" ? "testt" : "test"
        });
    };
  
    render() {
        const defaultImageryProvider = new UrlTemplateImageryProvider({
            url : "https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png"
        });
      return (
        <Viewer
          full
          ref={this.viewerRef}
          onSelectedEntityChange={this.handleSelectedEntityChanged}>

        <ImageryLayer imageryProvider={defaultImageryProvider} />

        <Entity
            name={this.state.name}
            position={Cartesian3.fromDegrees(61, 130, 100)}
            point={{ pixelSize: 10 }} />
        </Viewer>
      );
    }
};
`

![b873b053-5879-44ef-bee9-789d10415e80](https://user-images.githubusercontent.com/1075631/81995691-fe6a9200-9618-11ea-8f95-bb856a547e57.gif)

**Comment by benwiles1** [comment]
You are constructing a new imagryProvider on every render. It looks like it does not depend on any props or state though, so you should be able to just build it once inside the constructor.

**Comment by digennnj** [comment]
I am getting similar functionality with useEffect. I have an API call in my useEffect function which gets called every 5 seconds. With the data from the API I can set some state variables using "setMyVar()". This then updates the state variables and redraws a point in the Viewer. The weird thing is, this updates resets the clock.

I think this is because useEffect re-renders the view with every call. I am not sure if this is how this should work or if I am using state incorrectly with Resium.

**Comment by rot1024** [comment]
Try to move `new UrlTemplateImageryProvider(...)` outside the render function.

Before:

```jsx
  render() {
    const defaultImageryProvider = new UrlTemplateImageryProvider({
        url : "https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png"
    });
```

After:

```jsx
  defaultImageryProvider = new UrlTemplateImageryProvider({
    url : "https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png"
  });

  render() {
    // ...
    <ImageryLayer imageryProvider={this.defaultImageryProvider} />
```

**Comment by Chingili** [comment]
I think I have the same issue. When I update variable in parent that holds Entities as children, they all get redrawn

**Comment by vlkpa** [comment]
Same as you guys, when state of my component with `Viewer` is changed (with `useState()` or `useEffect()` hooks) - `ImageLayer` is reloaded. Is there some way how to fix this?

**Comment by rot1024** [comment]
`imageProvider` prop of `ImageryLayer` component is read-only and is not changeable because `ImageProvider` of `ImageryLayer` of Cesium API is also read-only. 

If the imageProvider is static, you can use outside const variable or `useMemo` hook as described in this page.

If you want to change the imageProvider dynamically, you cannot avoid regenerating the ImageryLayer. If you want to completely suppress warnings, key props can be used:

```jsx
const imageProvider = useMemo(() => new UrlTemplateImageryProvider({ url }), [url]);

return <ImageryLayer key={url} imageryProvider={imageProvider} />;
```

We are also considering suppressing the warnings. Either way, please understand that the imageProvider is read-only.
