### ISSUE TITLE
Cesium polyline is not rendering, when state variable changes

### ISSUE THREAD

**Issue by ats1999** [darwin-education/resium#465]
Problem description https://stackoverflow.com/questions/65632650/cesium-polyline-is-not-rendering-when-state-variable-changes

**Comment by rot1024** [comment]
That question is already answered.

**Comment by chriswalz-bg** [comment]
@rot1024 can you link to where it was answered

**Comment by rot1024** [comment]
Sorry. I didn't read that page in detail, so I misunderstood.

I've read the code, but so far I can't figure out why.

I tried the following code:

```jsx
import React, { useState } from "react";
import { Cartesian3, Color } from "cesium";
import { Viewer, Entity, PolylineGraphics } from "resium";

const positions = Cartesian3.fromDegreesArrayHeights([0, 0, 1000, 100, 100, 1000]);

const App = () => {
  const [s, ss] = useState(0);
  useEffect(() => {
    const i = setInterval(() => ss(v => v + 1), 1000);
    return () => clearInterval(i);
  }, []);

  return (
    <Viewer full>
      <Entity>
        <PolylineGraphics
          show
          width={3}
          material={Color.RED}
          positions={positions}
        />
      </Entity>
      <div style={{ position: "absolute", left: "0", top: "0", color: "#fff" }}>{s}</div>
    </Viewer>
  );
};

export default App;
```
Result (Cesium 1.82.1, Resium v1.13.1):

![Kapture 2021-06-18 at 11 34 10](https://user-images.githubusercontent.com/3888696/122497970-47b1c000-d029-11eb-84ee-70f980ae6423.gif)

As you can see, the polylines are displayed successfully even though there was a state update, so there seems to be no problem with Cesium or Resium itself.

Tip: `Cartesian3.fromDegreesArrayHeights(positions)` should be placed outside the component. This will reduce the flickering of the screen.

Unfortunately, the cause is not clear. Perhaps the component itself is not displaying, or perhaps there is a mistake in the polyline data. Or maybe your Cesium or Resium is old and you have stepped on some bug (I recommend upgrading).

If you can provide us with the smallest amount of self-contained code that causes the problem, we may be able to clarify the issue further.

**Comment by chriswalz-bg** [comment]
@rot1024 The problem for me was using `Cartesian3.fromDegreesArrayHeights(positions)` inside my functional component. The line wouldn't render at all. Neither would other PolylineGraphics *even if their positions were outside of the component*.   

How do you recommend updating state if you can't use it within the component? Ideally, I'd like to use the `useState()` hook

**Comment by chriswalz-bg** [comment]
Here's a minimal non-working example 


```
import React, { useRef } from 'react'
import { Cartesian3, Color, Viewer as CesiumViewer } from 'cesium'
import { CesiumComponentRef, Entity, PolylineGraphics, Viewer } from 'resium'

const App = () => {
    const viewerRef = useRef<CesiumComponentRef<CesiumViewer>>(null)

    const positionsA = Cartesian3.fromDegreesArrayHeights([-30, 0, 1000, 100, 100, 1000])

    return (
        <>
            <Viewer ref={viewerRef}>
                <Entity>
                    <PolylineGraphics show width={3} material={Color.RED} positions={positionsA} />
                </Entity>
            </Viewer>
        </>
    )
}

export default App
```

![image](https://user-images.githubusercontent.com/79238169/122829201-b3f42400-d2b4-11eb-9f7f-5030bb7befd5.png)

And here it is when `positionsA`  is outside the functional component 

![image](https://user-images.githubusercontent.com/79238169/122829298-d2f2b600-d2b4-11eb-86f1-13d04910e889.png)
